In [309]:
import pandas as pd
import numpy as np

In [310]:
ira = pd.read_excel('C://Users//Admin//Desktop//Devs//anal//ira.xlsx')

In [311]:
ira

                date_visit            id
0      27.08.2025 23:57:32  2.768828e+10
1      27.08.2025 23:57:33  2.768828e+10
2      27.08.2025 23:57:35  2.768828e+10
3      27.08.2025 23:57:36  2.768828e+10
4      27.08.2025 23:57:40  2.768828e+10
...                    ...           ...
30899  28.08.2025 12:18:36  9.585820e+10
30900  28.08.2025 12:18:37  9.585820e+10
30901  28.08.2025 12:18:38  9.585820e+10
30902  28.08.2025 12:18:39  9.585820e+10
30903  28.08.2025 12:18:40  9.585820e+10

[30904 rows x 2 columns]

Задача: убрать из данных записи о ложных входах пользователей (разница между входами менее 20 сек)

In [312]:
ira.dtypes

date_visit     object
id            float64
dtype: object

In [313]:
ira.date_visit = pd.to_datetime(ira.date_visit)

In [314]:
ira.isna().sum() #проверим на пропуски и удалим строки с пропусками

date_visit      0
id            107
dtype: int64

In [315]:
ira = ira.dropna()

In [316]:
ira

               date_visit            id
0     2025-08-27 23:57:32  2.768828e+10
1     2025-08-27 23:57:33  2.768828e+10
2     2025-08-27 23:57:35  2.768828e+10
3     2025-08-27 23:57:36  2.768828e+10
4     2025-08-27 23:57:40  2.768828e+10
...                   ...           ...
30899 2025-08-28 12:18:36  9.585820e+10
30900 2025-08-28 12:18:37  9.585820e+10
30901 2025-08-28 12:18:38  9.585820e+10
30902 2025-08-28 12:18:39  9.585820e+10
30903 2025-08-28 12:18:40  9.585820e+10

[30797 rows x 2 columns]

In [328]:
ira_gr = ira.groupby('id', as_index=False).agg(lambda x: list(x))
ira_gr #формируем для каждого пользователя список из его timestamp

                id                                         date_visit
0     2.790401e+08  [2025-08-28 08:11:45, 2025-08-28 08:11:46, 202...
1     3.006169e+08  [2025-08-28 06:02:14, 2025-08-28 06:02:15, 202...
2     3.100852e+08  [2025-08-28 09:26:07, 2025-08-28 09:26:10, 202...
3     4.250000e+08  [2025-08-28 07:40:03, 2025-08-28 07:40:04, 202...
4     4.262511e+08  [2025-08-28 07:33:07, 2025-08-28 07:33:08, 202...
...            ...                                                ...
1145  9.962530e+10  [2025-08-28 11:26:20, 2025-08-28 11:26:21, 202...
1146  9.967453e+10         [2025-08-28 10:14:44, 2025-08-28 10:14:45]
1147  9.974584e+10  [2025-08-28 11:20:53, 2025-08-28 11:20:54, 202...
1148  9.976705e+10  [2025-08-28 10:29:35, 2025-08-28 10:29:36, 202...
1149  9.981854e+10  [2025-08-28 09:18:39, 2025-08-28 09:18:40, 202...

[1150 rows x 2 columns]

In [329]:
ira_gr.date_visit = ira_gr.date_visit.apply(lambda x: sorted(x)) #на всякий случай отсортирум таймштапы в списках по возрастанию
ira_gr

                id                                         date_visit
0     2.790401e+08  [2025-08-28 08:11:45, 2025-08-28 08:11:46, 202...
1     3.006169e+08  [2025-08-28 06:02:14, 2025-08-28 06:02:15, 202...
2     3.100852e+08  [2025-08-28 09:26:07, 2025-08-28 09:26:10, 202...
3     4.250000e+08  [2025-08-28 07:40:03, 2025-08-28 07:40:04, 202...
4     4.262511e+08  [2025-08-28 07:33:07, 2025-08-28 07:33:08, 202...
...            ...                                                ...
1145  9.962530e+10  [2025-08-28 11:26:20, 2025-08-28 11:26:21, 202...
1146  9.967453e+10         [2025-08-28 10:14:44, 2025-08-28 10:14:45]
1147  9.974584e+10  [2025-08-28 11:20:53, 2025-08-28 11:20:54, 202...
1148  9.976705e+10  [2025-08-28 10:29:35, 2025-08-28 10:29:36, 202...
1149  9.981854e+10  [2025-08-28 09:18:39, 2025-08-28 09:18:40, 202...

[1150 rows x 2 columns]

In [330]:
def ind_delete(list_):
    del_list = []
    for i in range(1, len(list_)):
        if (list_[i]-list_[i-1])<dt.timedelta(0, 20):
            del_list.append(i)
    return del_list        #создание списка индексов, которые надо удалить из списка дататайм

In [331]:
ira_gr['in_del'] = ira_gr.date_visit.apply(lambda x: ind_delete(x))
ira_gr

,id,date_visit,in_del
0,2.790401e+08,"[2025-08-28 08:11:45, 2025-08-28 08:11:46, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1,3.006169e+08,"[2025-08-28 06:02:14, 2025-08-28 06:02:15, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15..."
2,3.100852e+08,"[2025-08-28 09:26:07, 2025-08-28 09:26:10, 202...","[1, 2, 3]"
3,4.250000e+08,"[2025-08-28 07:40:03, 2025-08-28 07:40:04, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
4,4.262511e+08,"[2025-08-28 07:33:07, 2025-08-28 07:33:08, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
...,...,...,...
1145,9.962530e+10,"[2025-08-28 11:26:20, 2025-08-28 11:26:21, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14..."
1146,9.967453e+10,"[2025-08-28 10:14:44, 2025-08-28 10:14:45]",[1]
1147,9.974584e+10,"[2025-08-28 11:20:53, 2025-08-28 11:20:54, 202...","[1, 2, 3, 4]"
1148,9.976705e+10,"[2025-08-28 10:29:35, 2025-08-28 10:29:36, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9]"
1149,9.981854e+10,"[2025-08-28 09:18:39, 2025-08-28 09:18:40, 202...","[1, 2, 3, 4, 5]"

def multi_delete(list_, ind):  
    indexes = sorted(ind, reverse=True)
    for index in indexes:
        del list_[index]
    return list_  #удаление из списка date_visit элементов с индексами in_del - пытался с ней, но не работает нормально

In [332]:
def new_list(list_, ind):
    n_list = []
    for i in range(len(list_)):
        if i not in ind:
            n_list.append(list_[i])
    return n_list        #создание списка дататаймов, которые должны остаться

In [333]:
res = []
for row in ira_gr.itertuples(index=False):
    res.append(new_list(row.date_visit, row.in_del))
ira_gr['new_date_visit'] = res #cоздаем колонку со списком дататаймов с разницей более 20 сек

In [334]:
ira_gr

,id,date_visit,in_del,new_date_visit
0,2.790401e+08,"[2025-08-28 08:11:45, 2025-08-28 08:11:46, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[2025-08-28 08:11:45]
1,3.006169e+08,"[2025-08-28 06:02:14, 2025-08-28 06:02:15, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 15...","[2025-08-28 06:02:14, 2025-08-28 06:03:59, 202..."
2,3.100852e+08,"[2025-08-28 09:26:07, 2025-08-28 09:26:10, 202...","[1, 2, 3]",[2025-08-28 09:26:07]
3,4.250000e+08,"[2025-08-28 07:40:03, 2025-08-28 07:40:04, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[2025-08-28 07:40:03]
4,4.262511e+08,"[2025-08-28 07:33:07, 2025-08-28 07:33:08, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...","[2025-08-28 07:33:07, 2025-08-28 07:34:13, 202..."
...,...,...,...,...
1145,9.962530e+10,"[2025-08-28 11:26:20, 2025-08-28 11:26:21, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14...",[2025-08-28 11:26:20]
1146,9.967453e+10,"[2025-08-28 10:14:44, 2025-08-28 10:14:45]",[1],[2025-08-28 10:14:44]
1147,9.974584e+10,"[2025-08-28 11:20:53, 2025-08-28 11:20:54, 202...","[1, 2, 3, 4]",[2025-08-28 11:20:53]
1148,9.976705e+10,"[2025-08-28 10:29:35, 2025-08-28 10:29:36, 202...","[1, 2, 3, 4, 5, 6, 7, 8, 9]",[2025-08-28 10:29:35]
1149,9.981854e+10,"[2025-08-28 09:18:39, 2025-08-28 09:18:40, 202...","[1, 2, 3, 4, 5]",[2025-08-28 09:18:39]

In [335]:
ira_gr = ira_gr.drop(['date_visit', 'in_del'], axis=1)

In [336]:
ira_gr = ira_gr.rename(columns={'new_date_visit': 'date_visit'})
ira_gr #удалим лишние колонки

                id                                         date_visit
0     2.790401e+08                              [2025-08-28 08:11:45]
1     3.006169e+08  [2025-08-28 06:02:14, 2025-08-28 06:03:59, 202...
2     3.100852e+08                              [2025-08-28 09:26:07]
3     4.250000e+08                              [2025-08-28 07:40:03]
4     4.262511e+08  [2025-08-28 07:33:07, 2025-08-28 07:34:13, 202...
...            ...                                                ...
1145  9.962530e+10                              [2025-08-28 11:26:20]
1146  9.967453e+10                              [2025-08-28 10:14:44]
1147  9.974584e+10                              [2025-08-28 11:20:53]
1148  9.976705e+10                              [2025-08-28 10:29:35]
1149  9.981854e+10                              [2025-08-28 09:18:39]

[1150 rows x 2 columns]

In [339]:
ira_gr = ira_gr.explode('date_visit')
ira_gr #взрываем списки

                id          date_visit
0     2.790401e+08 2025-08-28 08:11:45
1     3.006169e+08 2025-08-28 06:02:14
1     3.006169e+08 2025-08-28 06:03:59
1     3.006169e+08 2025-08-28 11:09:32
2     3.100852e+08 2025-08-28 09:26:07
...            ...                 ...
1145  9.962530e+10 2025-08-28 11:26:20
1146  9.967453e+10 2025-08-28 10:14:44
1147  9.974584e+10 2025-08-28 11:20:53
1148  9.976705e+10 2025-08-28 10:29:35
1149  9.981854e+10 2025-08-28 09:18:39

[2817 rows x 2 columns]

In [340]:
ira_gr = ira_gr.reindex(columns=['date_visit', 'id']) #возвращаем исходное положение колонок

In [341]:
ira_gr

              date_visit            id
0    2025-08-28 08:11:45  2.790401e+08
1    2025-08-28 06:02:14  3.006169e+08
1    2025-08-28 06:03:59  3.006169e+08
1    2025-08-28 11:09:32  3.006169e+08
2    2025-08-28 09:26:07  3.100852e+08
...                  ...           ...
1145 2025-08-28 11:26:20  9.962530e+10
1146 2025-08-28 10:14:44  9.967453e+10
1147 2025-08-28 11:20:53  9.974584e+10
1148 2025-08-28 10:29:35  9.976705e+10
1149 2025-08-28 09:18:39  9.981854e+10

[2817 rows x 2 columns]